/*
 * File: app/view/personal/Create.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enterprise.view.personal.Create', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personalcreate',

    requires: [
        'Enterprise.view.personal.CreateViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Segmented',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'personalcreate'
    },
    width: 640,
    iconCls: 'add',
    title: '创建员工',

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                dockedItems: [
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            {
                                xtype: 'tbfill'
                            },
                            {
                                xtype: 'segmentedbutton',
                                items: [
                                    me.processMyButton({
                                        text: 'MyButton'
                                    }),
                                    {
                                        text: 'MyButton'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processMyButton: function(config) {
        return config;
    }

});