/*
 * File: app/view/personal/List.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enterprise.overrides.view.user.List', {
    override: 'CACS.view.user.List',
    alias: 'widget.personallist',

    requires: [
        'Enterprise.view.personal.ListViewModel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.tree.Panel',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'personallist'
    },
    bodyBorder: true,
    iconCls: 'user',
    title: '员工管理',
    store: 'Personals',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'Username',
            text: '用户名'
        },
        {
            xtype: 'gridcolumn',
            text: '姓名'
        },
        {
            xtype: 'gridcolumn',
            text: '邮箱'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    href: '#enterprise/personal/create',
                    hrefTarget: '_self',
                    iconCls: 'add',
                    text: '添加'
                }
            ]
        },
        {
            xtype: 'treepanel',
            dock: 'left',
            border: false,
            width: 250,
            bodyBorder: true
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true
        }
    ]

});