/*
 * File: app/controller/Department.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Enterprise.controller.Department', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.app.route.Route'
    ],

    models: [
        'Department'
    ],
    stores: [
        'Departments'
    ],
    views: [
        'department.List'
    ],

    routes: {
        'enterprise/department/list': 'departmentList'
    },

    departmentList: function() {
        this.windowAction({
            view:'department.List'
        });
    }

});
